import Image from "next/image";
import { ArrowRight, Check, ChevronDown, CircleGauge, ClipboardCheck, MessagesSquare, Route, Sparkles, Target } from "lucide-react";
import { Container } from "@/components/ui/container"; import { Brand } from "@/components/ui/brand"; import { siteContent as c } from "@/content/landing-page"; import { LeadForm } from "@/components/forms/lead-form";
const icons=[Target,ClipboardCheck,MessagesSquare,Sparkles];
export function Hero(){return <section id="inicio" className="hero hero-image"><Image className="hero-background" src="/images/energy-hero-background.png" alt="Símbolo da Energy em composição branca com iluminação laranja" fill priority sizes="100vw"/><div className="hero-overlay" aria-hidden="true"/><Container className="hero-message"><span className="eyebrow">ENERGIA SOLAR • ENERGY</span><h1>Energia inteligente para um futuro mais <em>eficiente.</em></h1><p>Soluções solares orientadas ao seu consumo, ao seu espaço e às decisões que realmente importam.</p><div className="actions"><a className="button" href="#contato">{c.cta.primary}<ArrowRight/></a><a className="hero-link" href="#solucoes">Conhecer soluções</a></div><small><Check aria-hidden="true"/> Atendimento próximo, do primeiro contato à proposta.</small></Container><a className="scroll-indicator" href="#solucao" aria-label="Ir para a próxima seção"><span>Continue</span><ChevronDown aria-hidden="true"/></a></section>}
export function Trust(){return <section className="trust" aria-label="Informações comerciais a confirmar"><Container><p>INFORMAÇÕES AGUARDANDO VALIDAÇÃO</p><div>{c.trust.map(x=><span key={x}>{x}</span>)}</div></Container></section>}
export function ProblemSolution(){return <section id="solucao" className="section"><Container><div className="section-heading"><span>{c.problem.eyebrow}</span><h2>{c.problem.title}</h2></div><div className="split"><article><span className="number">01</span><h3>{c.problem.problemTitle}</h3><p>{c.problem.problemText}</p></article><article className="accent-card"><span className="number">02</span><h3>{c.problem.solutionTitle}</h3><p>{c.problem.solutionText}</p></article></div></Container></section>}
export function Benefits(){return <section id="beneficios" className="section section-soft"><Container><div className="section-heading"><span>VALOR PARA O CLIENTE</span><h2>Uma jornada comercial mais clara.</h2><p>Benefícios de uma abordagem estruturada — ajuste-os quando a oferta oficial estiver definida.</p></div><div className="card-grid">{c.benefits.map((x,i)=>{const Icon=icons[i];return <article className="benefit" key={x.title}><Icon/><h3>{x.title}</h3><p>{x.text}</p></article>})}</div></Container></section>}
export function Process(){return <section id="processo" className="section dark-section"><Container><div className="section-heading"><span>COMO FUNCIONA</span><h2>Do primeiro contato a uma proposta coerente.</h2></div><ol className="process">{c.process.map((x,i)=><li key={x.title}><span>{String(i+1).padStart(2,"0")}</span><h3>{x.title}</h3><p>{x.text}</p></li>)}</ol></Container></section>}
export function Differentiators(){return <section className="section"><Container><div className="section-heading"><span>FORMA DE TRABALHAR</span><h2>Critérios que facilitam uma boa decisão.</h2></div><div className="comparison" role="table" aria-label="Comparação de abordagens"><div className="compare-row compare-head" role="row"><span>Critério</span><span>Abordagem comum</span><span>Abordagem proposta</span></div>{c.differentiators.map(x=><div className="compare-row" role="row" key={x.label}><strong>{x.label}</strong><span>{x.traditional}</span><span><Check/>{x.energy}</span></div>)}</div></Container></section>}
export function Evidence(){return <section className="section section-soft"><Container><div className="evidence"><CircleGauge/><div><span className="eyebrow dark">EVIDÊNCIAS COMERCIAIS</span><h2>Espaço pronto para dados reais.</h2><p>Métricas, resultados e depoimentos não foram publicados porque ainda não foram fornecidos. Assim que validados, podem ser incluídos no arquivo central de conteúdo.</p></div></div></Container></section>}
export function FinalCta(){return <section className="final-cta"><Container><Brand compact/><div><h2>Vamos entender o que precisa avançar?</h2><p>Compartilhe seu contexto para a Energy avaliar o próximo passo.</p></div><a className="button" href="#contato">{c.cta.primary}<ArrowRight/></a></Container></section>}
export function Contact(){return <section id="contato" className="section contact"><Container><div className="contact-copy"><span className="eyebrow dark">CONTATO</span><h2>Comece pelo contexto.</h2><p>Preencha os campos ao lado. Nenhum dado será tratado como lead enviado enquanto a integração não estiver configurada.</p><div className="contact-point"><Route/><div><strong>Área de atendimento</strong><span>{c.contact.location}</span></div></div></div><div className="form-card"><h3>Conte sobre sua necessidade</h3><p>Todos os campos são obrigatórios.</p><LeadForm/></div></Container></section>}
