export const siteContent = {
  brand: "Energy",
  seo: {
    title: "Energy | Energia solar para decisões mais eficientes",
    description: "Converse com a Energy sobre energia solar e descubra o caminho mais adequado para a sua necessidade.",
  },
  contact: { email: "[E-MAIL PENDENTE]", whatsappUrl: "", location: "[ÁREA DE ATENDIMENTO PENDENTE]" },
  navigation: [
    { label: "Soluções", href: "#solucoes" }, { label: "Quem somos", href: "#quem-somos" },
    { label: "Processo", href: "#processo" }, { label: "FAQ", href: "#faq" },
  ],
  cta: { primary: "Solicitar uma proposta", secondary: "Falar com um especialista" },
  hero: {
    eyebrow: "ENERGIA SOLAR • PROJETO ORIENTADO À SUA NECESSIDADE",
    titleStart: "Energia solar para uma escolha",
    titleAccent: "mais consciente.",
    description: "A Energy entende o seu perfil de consumo e o contexto do imóvel para orientar os próximos passos de uma solução de energia solar.",
    trust: "Contato direto • Retorno conforme disponibilidade da equipe",
  },
  trust: ["[SEGMENTOS ATENDIDOS]", "[CERTIFICAÇÃO]", "[CLIENTE OU PARCEIRO]", "[INDICADOR REAL]"],
  problem: {
    eyebrow: "ENERGIA SOLAR COM CONTEXTO", title: "Uma boa decisão começa antes da instalação.",
    problemTitle: "O desafio", problemText: "Consumo, características do imóvel e objetivos diferentes exigem uma análise cuidadosa. Uma recomendação genérica pode não refletir a necessidade real.",
    solutionTitle: "A resposta Energy", solutionText: "A Energy começa pelo entendimento do cenário para orientar uma solução de energia solar coerente com as informações levantadas.",
  },
  benefits: [
    { title: "Análise do cenário", text: "Uma conversa sobre consumo, imóvel, prioridades e condições relevantes para o projeto solar." },
    { title: "Proposta compreensível", text: "Solução recomendada e próximos passos apresentados de forma clara para facilitar a decisão." },
    { title: "Contato próximo", text: "Um canal direto para reduzir desencontros e manter as conversas relevantes." },
    { title: "Projeto orientado à demanda", text: "A recomendação parte das informações do cliente, sem tratar necessidades diferentes como se fossem iguais." },
  ],
  solutions: [
    { eyebrow: "PROJETO SOLAR", title: "Energia solar para residências", text: "Uma solução dimensionada a partir do perfil de consumo e das características do imóvel.", image: "/images/solar/projeto-residencial.jpg", alt: "Painéis solares instalados em telhado residencial" },
    { eyebrow: "EXECUÇÃO", title: "Instalação de painéis solares", text: "Planejamento e execução técnica para transformar o projeto em um sistema solar instalado.", image: "/images/solar/equipe-instalacao.jpg", alt: "Profissionais realizando a instalação de painéis solares" },
    { eyebrow: "CUIDADO CONTÍNUO", title: "Manutenção de sistemas solares", text: "Avaliação das condições do sistema e intervenções necessárias para preservar seu funcionamento.", image: "/images/solar/manutencao-paineis.jpg", alt: "Sistema de painéis solares instalado sobre telhado" },
    { eyebrow: "ESCALA", title: "Soluções para empresas e propriedades", text: "Análise orientada ao contexto de consumo para projetos que exigem maior área e capacidade.", image: "/images/solar/paineis-solares.jpg", alt: "Conjunto amplo de painéis solares" },
    { eyebrow: "ENERGIA RENOVÁVEL", title: "Um caminho para uma matriz mais limpa", text: "Tecnologia solar aplicada a uma estratégia de energia alinhada às necessidades de cada operação.", image: "/images/solar/energia-renovavel.jpg", alt: "Painéis solares e aerogeradores em paisagem ao entardecer" },
  ],
  process: [
    { title: "Você compartilha o cenário", text: "Conte sobre o imóvel, o consumo e o objetivo com energia solar." },
    { title: "A Energy avalia", text: "A equipe analisa os dados iniciais e identifica informações complementares." },
    { title: "Alinhamos o projeto", text: "Uma conversa valida necessidades, condições e próximos passos." },
    { title: "Você recebe a proposta", text: "A solução solar recomendada é apresentada para sua avaliação." },
  ],
  differentiators: [
    { label: "Ponto de partida", traditional: "Oferta previamente definida", energy: "Entendimento da necessidade" },
    { label: "Comunicação", traditional: "Informação dispersa", energy: "Próximos passos explícitos" },
    { label: "Decisão", traditional: "Critérios pouco visíveis", energy: "Contexto organizado para avaliar" },
  ],
  metrics: [],
  testimonial: null,
  faq: [
    { q: "O que a Energy oferece?", a: "A Energy atua com energia solar. Os detalhes sobre modalidades, serviços incluídos e segmentos atendidos ainda precisam ser confirmados pela empresa." },
    { q: "Para quais empresas a solução é indicada?", a: "O perfil de cliente ideal ainda não foi definido no conteúdo. Informe seu setor, contexto e objetivo para que a Energy avalie a aderência." },
    { q: "Como começa o atendimento?", a: "O primeiro passo é informar sua necessidade e alguns dados do contexto. A equipe poderá solicitar informações complementares antes de recomendar o próximo caminho." },
    { q: "Existe uma proposta padrão?", a: "A página não publica pacotes ou preços porque essas informações não foram fornecidas. As condições devem ser apresentadas pela equipe após o entendimento da demanda." },
    { q: "Qual é o prazo de retorno?", a: "Ainda não há um prazo comercial oficial informado. O retorno depende da disponibilidade da equipe." },
    { q: "Meus dados ficam seguros?", a: "Os dados são enviados apenas ao endpoint configurado pelo responsável do site. Consulte a política de privacidade antes de enviar." },
  ],
  pending: ["Segmentos atendidos", "Serviços solares incluídos", "Cliente ideal", "Diferencial comprovável", "WhatsApp", "E-mail", "Área de atendimento", "Garantias", "Provas sociais", "Métricas", "Depoimento"],
} as const;
